version: '3.8'

services:
  test_db:
    image: postgres:latest
    container_name: test_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pvz_test_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pvz_test_db"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "5437:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data

volumes:
  test_postgres_data:
